package model;

/**
 * Constructs all the maps of the game using GameObjects, Enemies, and Player.
 */
public class GameMap {
  public ArrayList<GameObject> home = new ArrayList<GameObject>();
  public ArrayList<GameObject> home1 = new ArrayList<GameObject>();
  public ArrayList<GameObject> home2 = new ArrayList<GameObject>();
  public ArrayList<GameObject> desert = new ArrayList<GameObject>();
  public ArrayList<GameObject> river = new ArrayList<GameObject>();
  public ArrayList<GameObject> shop = new ArrayList<GameObject>();
  public ArrayList<GameObject> mountain = new ArrayList<GameObject>();
  public ArrayList<GameObject> dungeon1 = new ArrayList<GameObject>();
  public ArrayList<GameObject> dungeon2 = new ArrayList<GameObject>();
  public ArrayList<GameObject> dungeon3 = new ArrayList<GameObject>();
  
  //Creating home
  home.add(new GameObject(new Point2D.Double(5, 6)));
  home.add(new GameObject(new Point2D.Double(5, 7)));
  home.add(new GameObject(new Point2D.Double(5, 8)));
  home.add(new GameObject(new Point2D.Double(5, 9)));
  home.add(new GameObject(new Point2D.Double(5, 10)));
  home.add(new GameObject(new Point2D.Double(5, 11)));
  home.add(new GameObject(new Point2D.Double(5, 12)));
  home.add(new GameObject(new Point2D.Double(5, 13)));
  home.add(new GameObject(new Point2D.Double(6, 6)));
  home.add(new GameObject(new Point2D.Double(6, 7)));
  home.add(new PlayerClass(new Point2D.Double(6, 9)));
  home.add(new GameObject(new Point2D.Double(6, 10)));
  home.add(new GameObject(new Point2D.Double(6, 12)));
  home.add(new GameObject(new Point2D.Double(6, 13)));
  home.add(new GameObject(new Point2D.Double(7, 6)));
  home.add(new GameObject(new Point2D.Double(7, 7)));
  home.add(new GameObject(new Point2D.Double(8, 6)));
  home.add(new GameObject(new Point2D.Double(8, 7)));
  home.add(new GameObject(new Point2D.Double(8, 8)));
  home.add(new GameObject(new Point2D.Double(8, 12)));
  home.add(new GameObject(new Point2D.Double(8, 13)));
  home.add(new GameObject(new Point2D.Double(9, 6)));
  home.add(new GameObject(new Point2D.Double(9, 7)));
  home.add(new GameObject(new Point2D.Double(9, 6)));
  home.add(new GameObject(new Point2D.Double(9, 12)));
  home.add(new GameObject(new Point2D.Double(9, 13)));
  home.add(new GameObject(new Point2D.Double(10, 6)));
  home.add(new GameObject(new Point2D.Double(10, 7)));
  home.add(new GameObject(new Point2D.Double(10, 8)));
  home.add(new GameObject(new Point2D.Double(10, 11)));
  home.add(new GameObject(new Point2D.Double(10, 12)));
  home.add(new GameObject(new Point2D.Double(10, 13)));
  home.add(new GameObject(new Point2D.Double(11, 6)));
  home.add(new GameObject(new Point2D.Double(11, 7)));
  home.add(new GameObject(new Point2D.Double(11, 8)));
  home.add(new GameObject(new Point2D.Double(11, 9)));
  home.add(new GameObject(new Point2D.Double(11, 10)));
  home.add(new GameObject(new Point2D.Double(11, 11)));
  home.add(new GameObject(new Point2D.Double(11, 12)));
  home.add(new GameObject(new Point2D.Double(11, 13))); 
    
  
  //Creating home1
  home1.add(new GameObject(new Point2D.Double(0, 0)));  
  home1.add(new GameObject(new Point2D.Double(0, 1)));  
  home1.add(new GameObject(new Point2D.Double(0, 2)));  
  home1.add(new GameObject(new Point2D.Double(0, 3)));  
  home1.add(new GameObject(new Point2D.Double(0, 4)));  
  home1.add(new GameObject(new Point2D.Double(0, 5)));  
  home1.add(new GameObject(new Point2D.Double(0, 6)));  
  home1.add(new GameObject(new Point2D.Double(0, 7)));  
  home1.add(new GameObject(new Point2D.Double(0, 8)));  
  home1.add(new GameObject(new Point2D.Double(0, 9)));  
  home1.add(new GameObject(new Point2D.Double(0, 10)));  
  home1.add(new GameObject(new Point2D.Double(0, 11)));  
  home1.add(new GameObject(new Point2D.Double(0, 12)));  
  home1.add(new GameObject(new Point2D.Double(0, 13)));  
  home1.add(new GameObject(new Point2D.Double(1, 0)));  
  home1.add(new GameObject(new Point2D.Double(1, 1)));  
  home1.add(new GameObject(new Point2D.Double(1, 2)));  
  home1.add(new GameObject(new Point2D.Double(1, 4)));  
  home1.add(new GameObject(new Point2D.Double(1, 5)));  
  home1.add(new GameObject(new Point2D.Double(1, 6)));  
  home1.add(new GameObject(new Point2D.Double(1, 7)));  
  home1.add(new GameObject(new Point2D.Double(1, 8)));  
  home1.add(new GameObject(new Point2D.Double(1, 9)));  
  home1.add(new GameObject(new Point2D.Double(1, 10)));  
  home1.add(new GameObject(new Point2D.Double(1, 11)));  
  home1.add(new GameObject(new Point2D.Double(1, 12)));  
  home1.add(new GameObject(new Point2D.Double(1, 13)));  
  home1.add(new GameObject(new Point2D.Double(2, 0))); 
  home1.add(new GameObject(new Point2D.Double(2, 1)));
  home1.add(new GameObject(new Point2D.Double(2, 5)));
  home1.add(new GameObject(new Point2D.Double(2, 6)));
  home1.add(new GameObject(new Point2D.Double(3, 0))); 
  home1.add(new GameObject(new Point2D.Double(3, 1)));
  home1.add(new GameObject(new Point2D.Double(3, 2))); 
  home1.add(new GameObject(new Point2D.Double(4, 0))); 
  home1.add(new GameObject(new Point2D.Double(4, 1)));
  home1.add(new GameObject(new Point2D.Double(4, 2)));
  home1.add(new GameObject(new Point2D.Double(5, 0))); 
  home1.add(new GameObject(new Point2D.Double(5, 1)));
  home1.add(new GameObject(new Point2D.Double(5, 2)));
  home1.add(new GameObject(new Point2D.Double(5, 9))); 
  home1.add(new GameObject(new Point2D.Double(12, 5)));
  home1.add(new GameObject(new Point2D.Double(13, 4)));
  home1.add(new GameObject(new Point2D.Double(14, 3))); 
  home1.add(new GameObject(new Point2D.Double(8, 0)));
  home1.add(new GameObject(new Point2D.Double(9, 0)));
  home1.add(new GameObject(new Point2D.Double(10, 0)));
  home1.add(new GameObject(new Point2D.Double(11, 0)));
  home1.add(new GameObject(new Point2D.Double(12, 0)));
  home1.add(new GameObject(new Point2D.Double(13, 0)));
  home1.add(new GameObject(new Point2D.Double(14, 0)));
  home1.add(new GameObject(new Point2D.Double(15, 0)));
  home1.add(new GameObject(new Point2D.Double(16, 0)));
  home1.add(new GameObject(new Point2D.Double(17, 0)));
  home1.add(new GameObject(new Point2D.Double(8, 1)));
  home1.add(new GameObject(new Point2D.Double(9, 1)));
  home1.add(new GameObject(new Point2D.Double(10, 1)));
  home1.add(new GameObject(new Point2D.Double(11, 1)));
  home1.add(new GameObject(new Point2D.Double(12, 1)));
  home1.add(new GameObject(new Point2D.Double(13, 1)));
  home1.add(new GameObject(new Point2D.Double(14, 1)));
  home1.add(new GameObject(new Point2D.Double(15, 1)));
  home1.add(new GameObject(new Point2D.Double(16, 1)));
  home1.add(new GameObject(new Point2D.Double(17, 1)));
  home1.add(new GameObject(new Point2D.Double(17, 2)));
  home1.add(new GameObject(new Point2D.Double(17, 3)));
  home1.add(new GameObject(new Point2D.Double(17, 4)));
  home1.add(new GameObject(new Point2D.Double(17, 5)));
  home1.add(new GameObject(new Point2D.Double(17, 6)));
  home1.add(new GameObject(new Point2D.Double(17, 7)));
  home1.add(new GameObject(new Point2D.Double(2, 13))); 
  home1.add(new GameObject(new Point2D.Double(3, 13)));
  home1.add(new GameObject(new Point2D.Double(4, 13))); 
  home1.add(new GameObject(new Point2D.Double(5, 13))); 
  home1.add(new GameObject(new Point2D.Double(6, 13)));
  home1.add(new GameObject(new Point2D.Double(7, 13))); 
  home1.add(new GameObject(new Point2D.Double(8, 13))); 
  home1.add(new GameObject(new Point2D.Double(9, 13)));
  home1.add(new GameObject(new Point2D.Double(10, 13))); 
  home1.add(new GameObject(new Point2D.Double(11, 13))); 
  home1.add(new GameObject(new Point2D.Double(12, 13)));
  home1.add(new GameObject(new Point2D.Double(13, 13))); 
  home1.add(new GameObject(new Point2D.Double(14, 13))); 
  home1.add(new GameObject(new Point2D.Double(15, 13)));
  home1.add(new GameObject(new Point2D.Double(16, 13))); 
  home1.add(new GameObject(new Point2D.Double(17, 13))); 
  
  //Creating home2
  home2.add(new GameObject(new Point2D.Double(0, 0))); 
  home2.add(new GameObject(new Point2D.Double(0, 1))); 
  home2.add(new GameObject(new Point2D.Double(0, 2))); 
  home2.add(new GameObject(new Point2D.Double(0, 3))); 
  home2.add(new GameObject(new Point2D.Double(0, 4))); 
  home2.add(new GameObject(new Point2D.Double(0, 5))); 
  home2.add(new GameObject(new Point2D.Double(0, 6))); 
  home2.add(new GameObject(new Point2D.Double(0, 7))); 
  home2.add(new GameObject(new Point2D.Double(0, 8))); 
  home2.add(new GameObject(new Point2D.Double(0, 9))); 
  home2.add(new GameObject(new Point2D.Double(0, 10))); 
  home2.add(new GameObject(new Point2D.Double(0, 11))); 
  home2.add(new GameObject(new Point2D.Double(0, 12))); 
  home2.add(new GameObject(new Point2D.Double(0, 13))); 
  home2.add(new GameObject(new Point2D.Double(1, 0))); 
  home2.add(new GameObject(new Point2D.Double(1, 1))); 
  home2.add(new GameObject(new Point2D.Double(1, 4))); 
  home2.add(new GameObject(new Point2D.Double(1, 5)));
  home2.add(new GameObject(new Point2D.Double(1, 6))); 
  home2.add(new GameObject(new Point2D.Double(1, 9))); 
  home2.add(new GameObject(new Point2D.Double(1, 10))); 
  home2.add(new GameObject(new Point2D.Double(1, 13)));
  home2.add(new GameObject(new Point2D.Double(2, 0))); 
  home2.add(new GameObject(new Point2D.Double(2, 1))); 
  home2.add(new GameObject(new Point2D.Double(2, 13))); 
  home2.add(new GameObject(new Point2D.Double(3, 0))); 
  home2.add(new GameObject(new Point2D.Double(3, 1))); 
  home2.add(new GameObject(new Point2D.Double(3, 13))); 
  home2.add(new GameObject(new Point2D.Double(4, 0))); 
  home2.add(new GameObject(new Point2D.Double(4, 1))); 
  home2.add(new GameObject(new Point2D.Double(4, 13))); 
  home2.add(new GameObject(new Point2D.Double(5, 0))); 
  home2.add(new GameObject(new Point2D.Double(5, 1))); 
  home2.add(new GameObject(new Point2D.Double(6, 0))); 
  home2.add(new GameObject(new Point2D.Double(6, 1)));
  home2.add(new GameObject(new Point2D.Double(7, 0))); 
  home2.add(new GameObject(new Point2D.Double(7, 1))); 
  home2.add(new GameObject(new Point2D.Double(8, 0))); 
  home2.add(new GameObject(new Point2D.Double(8, 1))); 
  home2.add(new GameObject(new Point2D.Double(8, 3))); 
  home2.add(new GameObject(new Point2D.Double(9, 0))); 
  home2.add(new GameObject(new Point2D.Double(9, 1))); 
  home2.add(new GameObject(new Point2D.Double(12, 0))); 
  home2.add(new GameObject(new Point2D.Double(12, 1))); 
  home2.add(new GameObject(new Point2D.Double(13, 0))); 
  home2.add(new GameObject(new Point2D.Double(13, 1))); 
  home2.add(new GameObject(new Point2D.Double(14, 0))); 
  home2.add(new GameObject(new Point2D.Double(14, 1))); 
  home2.add(new GameObject(new Point2D.Double(14, 2))); 
  home2.add(new GameObject(new Point2D.Double(15, 0))); 
  home2.add(new GameObject(new Point2D.Double(15, 1)));  
  home2.add(new GameObject(new Point2D.Double(15, 6)));  
  home2.add(new GameObject(new Point2D.Double(16, 0))); 
  home2.add(new GameObject(new Point2D.Double(16, 1))); 
  home2.add(new GameObject(new Point2D.Double(17, 0))); 
  home2.add(new GameObject(new Point2D.Double(17, 1))); 
  home2.add(new GameObject(new Point2D.Double(7, 13))); 
  home2.add(new GameObject(new Point2D.Double(8, 13))); 
  home2.add(new GameObject(new Point2D.Double(9, 13))); 
  home2.add(new GameObject(new Point2D.Double(10, 13))); 
  home2.add(new GameObject(new Point2D.Double(11, 13))); 
  home2.add(new GameObject(new Point2D.Double(12, 13))); 
  home2.add(new GameObject(new Point2D.Double(13, 13))); 
  home2.add(new GameObject(new Point2D.Double(14, 13))); 
  home2.add(new GameObject(new Point2D.Double(15, 13))); 
  home2.add(new GameObject(new Point2D.Double(16, 13))); 
  home2.add(new GameObject(new Point2D.Double(17, 13))); 
  home2.add(new GameObject(new Point2D.Double(15, 11))); 
  home2.add(new GameObject(new Point2D.Double(15, 12))); 
  home2.add(new GameObject(new Point2D.Double(15, 13))); 
  home2.add(new GameObject(new Point2D.Double(16, 10))); 
  home2.add(new GameObject(new Point2D.Double(16, 11))); 
  home2.add(new GameObject(new Point2D.Double(16, 12))); 
  home2.add(new GameObject(new Point2D.Double(16, 13))); 
  home2.add(new GameObject(new Point2D.Double(17, 9))); 
  home2.add(new GameObject(new Point2D.Double(17, 10))); 
  home2.add(new GameObject(new Point2D.Double(17, 11))); 
  home2.add(new GameObject(new Point2D.Double(17, 12))); 
  home2.add(new GameObject(new Point2D.Double(17, 13))); 

  //Creating desert
  desert.add(new GameObject(new Point2D.Double(0, 0)));
  desert.add(new GameObject(new Point2D.Double(0, 1)));
  desert.add(new GameObject(new Point2D.Double(0, 2)));
  desert.add(new GameObject(new Point2D.Double(0, 3)));
  desert.add(new GameObject(new Point2D.Double(0, 4)));
  desert.add(new GameObject(new Point2D.Double(0, 5)));
  desert.add(new GameObject(new Point2D.Double(0, 6)));
  desert.add(new GameObject(new Point2D.Double(0, 7)));
  desert.add(new GameObject(new Point2D.Double(0, 8)));
  desert.add(new GameObject(new Point2D.Double(0, 9)));
  desert.add(new GameObject(new Point2D.Double(0, 10)));
  desert.add(new GameObject(new Point2D.Double(0, 11)));
  desert.add(new GameObject(new Point2D.Double(0, 12)));
  desert.add(new GameObject(new Point2D.Double(0, 13)));
  desert.add(new GameObject(new Point2D.Double(1, 13)));
  desert.add(new GameObject(new Point2D.Double(2, 13)));
  desert.add(new GameObject(new Point2D.Double(3, 13)));
  desert.add(new GameObject(new Point2D.Double(4, 13)));
  desert.add(new GameObject(new Point2D.Double(5, 13)));
  desert.add(new GameObject(new Point2D.Double(6, 13)));
  desert.add(new GameObject(new Point2D.Double(7, 13)));
  desert.add(new GameObject(new Point2D.Double(8, 13)));
  desert.add(new GameObject(new Point2D.Double(13, 13)));
  desert.add(new GameObject(new Point2D.Double(14, 13)));
  desert.add(new GameObject(new Point2D.Double(15, 13)));
  desert.add(new GameObject(new Point2D.Double(16, 13)));
  desert.add(new GameObject(new Point2D.Double(17, 0)));
  desert.add(new GameObject(new Point2D.Double(17, 1)));
  desert.add(new GameObject(new Point2D.Double(17, 2)));
  desert.add(new GameObject(new Point2D.Double(17, 3)));
  desert.add(new GameObject(new Point2D.Double(17, 4)));
  desert.add(new GameObject(new Point2D.Double(17, 5)));
  desert.add(new GameObject(new Point2D.Double(17, 6)));
  desert.add(new GameObject(new Point2D.Double(17, 7)));
  desert.add(new GameObject(new Point2D.Double(17, 8)));
  desert.add(new GameObject(new Point2D.Double(17, 9)));
  desert.add(new GameObject(new Point2D.Double(17, 10)));
  desert.add(new GameObject(new Point2D.Double(17, 11)));
  desert.add(new GameObject(new Point2D.Double(17, 12)));
  desert.add(new GameObject(new Point2D.Double(17, 13)));
  desert.add(new GameObject(new Point2D.Double(1, 0)));
  desert.add(new GameObject(new Point2D.Double(1, 1)));
  desert.add(new GameObject(new Point2D.Double(1, 2)));
  desert.add(new GameObject(new Point2D.Double(1, 3)));
  desert.add(new GameObject(new Point2D.Double(1, 6)));
  desert.add(new GameObject(new Point2D.Double(2, 0)));
  desert.add(new GameObject(new Point2D.Double(2, 1)));
  desert.add(new GameObject(new Point2D.Double(3, 0)));
  desert.add(new GameObject(new Point2D.Double(3, 1)));
  desert.add(new GameObject(new Point2D.Double(3, 7)));
  desert.add(new GameObject(new Point2D.Double(4, 0)));
  desert.add(new GameObject(new Point2D.Double(4, 1)));
  desert.add(new GameObject(new Point2D.Double(4, 4)));
  desert.add(new GameObject(new Point2D.Double(5, 0)));
  desert.add(new GameObject(new Point2D.Double(5, 1)));
  desert.add(new GameObject(new Point2D.Double(5, 9)));
  desert.add(new GameObject(new Point2D.Double(5, 10)));
  desert.add(new GameObject(new Point2D.Double(6, 0)));
  desert.add(new GameObject(new Point2D.Double(6, 1)));
  desert.add(new GameObject(new Point2D.Double(6, 2)));
  desert.add(new GameObject(new Point2D.Double(6, 3)));
  desert.add(new GameObject(new Point2D.Double(6, 4)));
  desert.add(new GameObject(new Point2D.Double(7, 0)));
  desert.add(new GameObject(new Point2D.Double(7, 1)));
  desert.add(new GameObject(new Point2D.Double(7, 2)));
  desert.add(new GameObject(new Point2D.Double(7, 3)));
  desert.add(new GameObject(new Point2D.Double(7, 4)));
  desert.add(new GameObject(new Point2D.Double(8, 0)));
  desert.add(new GameObject(new Point2D.Double(8, 1)));
  desert.add(new GameObject(new Point2D.Double(8, 2)));
  desert.add(new GameObject(new Point2D.Double(9, 0)));
  desert.add(new GameObject(new Point2D.Double(9, 1)));
  desert.add(new GameObject(new Point2D.Double(9, 2)));
  desert.add(new GameObject(new Point2D.Double(10, 0)));
  desert.add(new GameObject(new Point2D.Double(10, 1)));
  desert.add(new GameObject(new Point2D.Double(10, 2)));
  desert.add(new GameObject(new Point2D.Double(10, 3)));
  desert.add(new GameObject(new Point2D.Double(11, 0)));
  desert.add(new GameObject(new Point2D.Double(11, 1)));
  desert.add(new GameObject(new Point2D.Double(11, 2)));
  desert.add(new GameObject(new Point2D.Double(11, 3)));
  desert.add(new GameObject(new Point2D.Double(12, 0)));
  desert.add(new GameObject(new Point2D.Double(12, 1)));
  desert.add(new GameObject(new Point2D.Double(13, 0)));
  desert.add(new GameObject(new Point2D.Double(13, 1)));
  desert.add(new GameObject(new Point2D.Double(14, 0)));
  desert.add(new GameObject(new Point2D.Double(15, 0)));
  desert.add(new GameObject(new Point2D.Double(15, 1)));
  desert.add(new GameObject(new Point2D.Double(15, 2)));
  desert.add(new GameObject(new Point2D.Double(15, 4)));
  desert.add(new GameObject(new Point2D.Double(15, 5)));
  desert.add(new GameObject(new Point2D.Double(16, 0)));
  desert.add(new GameObject(new Point2D.Double(16, 11)));
  
  
  //Creating river


    
    
  
    
}
